import { Elementbeast, CharacterProfile, EpisodeGuide, ScannableObjectSample } from '../types/elementbeasts';

/**
 * Official Elementbeasts Database
 * Strictly based on the Production Bible by Alejandro Beltran Luna
 */

export const INITIAL_ELEMENTBEASTS: Elementbeast[] = [
  // --- ELEMENTOS PUROS (ÁTOMOS BASE) ---
  {
    id: 'hidrogeno',
    name: 'Hidrógeno',
    symbol: 'H',
    atomicNumber: 1,
    formula: 'H',
    isCompound: false,
    category: 'No Metales',
    state: 'Gaseoso',
    color: '#38bdf8',
    accentColor: '#0284c7',
    avatarEmoji: '✨',
    visualDescription: 'Pequeño espíritu esférico flotante y ultraligero que orbita a gran velocidad con un halo azul eléctrico.',
    lore: 'El elemento inicial otorgado a Leo por el Profesor Lantan. Es el átomo más abundante y ligero del universo, base de innumerables reacciones químicas.',
    reactionHistory: 'Capítulo 1, 2, 3, 4, 5, 6 y 10. Compañero insignia de Leo.',
    property: {
      name: 'Ligereza Primordial',
      description: 'Velocidad de reacción altísima y versatilidad para formar enlaces con cualquier elemento disponible.',
      effectCode: 'ELASTICO',
    },
    stats: {
      hp: 31, // Base ligero (30) + Masa (1.008)
      maxHp: 31,
      fuerza: 25,
      resistencia: 15,
      velocidad: 22, // Electronegatividad Pauling 2.20
      poderEspecial: 7, // pH neutro / balanceado
      masaAtomica: 1.008,
      durezaMohs: 0.5,
      puntoFusionC: -259.16,
      electronegatividad: 2.20,
      ph: 7.0,
    },
  },
  {
    id: 'carbono',
    name: 'Carbono',
    symbol: 'C',
    atomicNumber: 6,
    formula: 'C',
    isCompound: false,
    category: 'No Metales',
    state: 'Sólido',
    color: '#334155',
    accentColor: '#0f172a',
    avatarEmoji: '🐆',
    visualDescription: 'Imponente felino o pantera oscura con facetas cristalinas de diamante y grafito que reflejan destellos prismáticos.',
    lore: 'El elemento insignia de Yan. Capaz de crear enlaces covalentes cuádruples y adoptar formas alotrópicas desde el grafito hasta el diamante indestructible.',
    reactionHistory: 'Capítulo 2, 3, 5, 10. Utilizado por Yan para extinguir incendios con CO2 y forjar Carburo de Silicio.',
    property: {
      name: 'Tetravalencia Diamantina',
      description: 'Permite hibridaciones moleculares extremas y resistencia a cambios de estado repentinos.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 42, // Base ligero (30) + Masa (12.011)
      maxHp: 42,
      fuerza: 75, // Alta dureza diamante
      resistencia: 80,
      velocidad: 25, // Pauling 2.55
      poderEspecial: 7,
      masaAtomica: 12.011,
      durezaMohs: 10.0,
      puntoFusionC: 3550,
      electronegatividad: 2.55,
      ph: 7.0,
    },
  },
  {
    id: 'hierro',
    name: 'Hierro',
    symbol: 'Fe',
    atomicNumber: 26,
    formula: 'Fe',
    isCompound: false,
    category: 'Metales de Transición',
    state: 'Sólido',
    color: '#ea580c',
    accentColor: '#9a3412',
    avatarEmoji: '🦍',
    visualDescription: 'Poderoso gorila biónico blindado con placas férreas remachadas, emanando un brillo térmico incandescente.',
    lore: 'El elemento inicial de Ana. Representa la fuerza bruta, la tenacidad estructural y la base de las aleaciones más resistentes del mundo de Materia.',
    reactionHistory: 'Capítulo 2, 3, 5, 7, 8, 10. Usado por Ana para embestir a rivales y sintetizar Cementita y Ferrosilicio.',
    property: {
      name: 'Magnético',
      description: 'Reduce el daño a metales en 20 puntos y canaliza campos magnéticos de control.',
      effectCode: 'MAGNETICO',
    },
    stats: {
      hp: 106, // Base medio (50) + Masa (55.845)
      maxHp: 106,
      fuerza: 78,
      resistencia: 85,
      velocidad: 18, // Pauling 1.83
      poderEspecial: 7,
      masaAtomica: 55.845,
      durezaMohs: 4.5,
      puntoFusionC: 1538,
      electronegatividad: 1.83,
      ph: 7.0,
    },
  },
  {
    id: 'silicio',
    name: 'Silicio',
    symbol: 'Si',
    atomicNumber: 14,
    formula: 'Si',
    isCompound: false,
    category: 'Metaloides',
    state: 'Sólido',
    color: '#0284c7',
    accentColor: '#0369a1',
    avatarEmoji: '🤖',
    visualDescription: 'Criatura insectoide biomecánica de circuitos luminosos de silicio semiconductor y alas de placa solar.',
    lore: 'El elemento asignado a Kai. Es el cerebro analítico del equipo, capaz de calcular densidades de sustrato y filtrar impurezas en ríos y redes.',
    reactionHistory: 'Capítulo 2, 4, 5, 8, 9, 10. Usado por Kai para analizar suelos y crear Sílice, Ferrosilicio y cementos.',
    property: {
      name: 'Semiconductor Lógico',
      description: 'Calcula las debilidades del oponente y aumenta la precisión de las síntesis.',
      effectCode: 'CONDUCTOR',
    },
    stats: {
      hp: 58, // Base ligero (30) + Masa (28.085)
      maxHp: 58,
      fuerza: 65,
      resistencia: 70,
      velocidad: 19, // Pauling 1.90
      poderEspecial: 7,
      masaAtomica: 28.085,
      durezaMohs: 7.0,
      puntoFusionC: 1414,
      electronegatividad: 1.90,
      ph: 7.0,
    },
  },
  {
    id: 'nitrogeno',
    name: 'Nitrógeno',
    symbol: 'N',
    atomicNumber: 7,
    formula: 'N',
    isCompound: false,
    category: 'No Metales',
    state: 'Gaseoso',
    color: '#06b6d4',
    accentColor: '#0891b2',
    avatarEmoji: '🦎',
    visualDescription: 'Camaleón celeste criogénico con cola en espiral que exhala vaharadas de frío estabilizador instantáneo.',
    lore: 'Invocado por Yan en el Capítulo 1 para enfriar y estabilizar al Fósforo Blanco fuera de control en las afueras de Nobelia.',
    reactionHistory: 'Capítulo 1. Intervención decisiva de Yan para sofocar la combustión espontánea.',
    property: {
      name: 'Estabilización Criogénica',
      description: 'Absorbe calor violentamente (Reacción Endotérmica) y anula el estado de ignición del rival.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 44,
      maxHp: 44,
      fuerza: 30,
      resistencia: 20,
      velocidad: 30, // Pauling 3.04
      poderEspecial: 7,
      masaAtomica: 14.007,
      puntoFusionC: -210.0,
      electronegatividad: 3.04,
      ph: 7.0,
    },
  },
  {
    id: 'fosforo',
    name: 'Fósforo',
    symbol: 'P',
    atomicNumber: 15,
    formula: 'P',
    isCompound: false,
    category: 'No Metales',
    state: 'Sólido',
    color: '#10b981',
    accentColor: '#059669',
    avatarEmoji: '🦊',
    visualDescription: 'Zorro bioluminiscente de pelaje turquesa resplandeciente con collar de luz estelar fósforo.',
    lore: 'Encontrado inestable por Leo en el Capítulo 1. También usado por Yan y Ana para crear Fosfuro de Hierro y neutralizar al Manganeso.',
    reactionHistory: 'Capítulos 1, 3, 5. Capaz de emitir luminiscencia y reaccionar vivamente con metales.',
    property: {
      name: 'Lacerante',
      description: 'Cuando sus PV son reducidos a 0, provoca 20 pts de daño a sólidos y líquidos.',
      effectCode: 'LACERANTE',
    },
    stats: {
      hp: 61,
      maxHp: 61,
      fuerza: 45,
      resistencia: 35,
      velocidad: 22, // Pauling 2.19
      poderEspecial: 6,
      masaAtomica: 30.974,
      durezaMohs: 2.0,
      puntoFusionC: 44.15,
      electronegatividad: 2.19,
      ph: 6.0,
    },
  },
  {
    id: 'sodio',
    name: 'Sodio',
    symbol: 'Na',
    atomicNumber: 11,
    formula: 'Na',
    isCompound: false,
    category: 'Alcalinos',
    state: 'Sólido',
    color: '#f59e0b',
    accentColor: '#d97706',
    avatarEmoji: '🐢',
    visualDescription: 'Tortuga marina acorazada con cristales salinos relucientes y un barril dorsal de agua hiper-reactiva.',
    lore: 'Un elemento travieso y ultra veloz que causaba estragos en el granero del Capítulo 7 antes de ser neutralizado con Cloro.',
    reactionHistory: 'Capítulo 7, 10. Crea chispas de colores al contacto con agua.',
    property: {
      name: 'Hidrorreacción Explosiva',
      description: 'Si recibe un ataque en estado Líquido, reduce el daño al 50% y devuelve 40 pts de daño reactivo al atacante.',
      effectCode: 'HIDRORREACCION',
    },
    stats: {
      hp: 53,
      maxHp: 53,
      fuerza: 45,
      resistencia: 35,
      velocidad: 85, // Enorme prioridad reactiva
      poderEspecial: 12, // Muy alcalino
      masaAtomica: 22.990,
      durezaMohs: 0.5,
      puntoFusionC: 97.79,
      electronegatividad: 0.93,
      ph: 12.0,
    },
  },
  {
    id: 'potasio',
    name: 'Potasio',
    symbol: 'K',
    atomicNumber: 19,
    formula: 'K',
    isCompound: false,
    category: 'Alcalinos',
    state: 'Sólido',
    color: '#a855f7',
    accentColor: '#7e22ce',
    avatarEmoji: '🐍',
    visualDescription: 'Serpiente mística envuelta en llamas y relámpagos púrpuras violetas de plasma catiónico.',
    lore: 'Usado por estudiantes rivales en el combate 2v2 del Capítulo 5 contra el Magnesio de Ana.',
    reactionHistory: 'Capítulo 5. Genera sobrecargas eléctricas fulgurantes de color lila.',
    property: {
      name: 'Excitación Catiónica',
      description: 'Aplica el efecto de campo Excitación Eléctrica restando 20 de Fuerza a los Metales rivales.',
      effectCode: 'CONDUCTOR',
    },
    stats: {
      hp: 89,
      maxHp: 89,
      fuerza: 50,
      resistencia: 25,
      velocidad: 82,
      poderEspecial: 13,
      masaAtomica: 39.098,
      durezaMohs: 0.4,
      puntoFusionC: 63.5,
      electronegatividad: 0.82,
      ph: 13.0,
    },
  },
  {
    id: 'manganeso',
    name: 'Manganeso',
    symbol: 'Mn',
    atomicNumber: 25,
    formula: 'Mn',
    isCompound: false,
    category: 'Metales de Transición',
    state: 'Sólido',
    color: '#84cc16',
    accentColor: '#65a30d',
    avatarEmoji: '🐺',
    visualDescription: 'Hiena salvaje con armadura de cabeza y cristales prismáticos multicolores en el lomo.',
    lore: 'Utilizado por delincuentes en el bosque del Capítulo 3 para fracturar moléculas de oxígeno y desatar un incendio.',
    reactionHistory: 'Capítulo 3. Catalizador voraz de descomposición.',
    property: {
      name: 'Catalizador Agresivo',
      description: 'Acelera la rotura de enlaces enemigos aumentando el daño crítico en un 25%.',
      effectCode: 'OXIDANTE',
    },
    stats: {
      hp: 105,
      maxHp: 105,
      fuerza: 70,
      resistencia: 65,
      velocidad: 15,
      poderEspecial: 7,
      masaAtomica: 54.938,
      durezaMohs: 6.0,
      puntoFusionC: 1246,
      electronegatividad: 1.55,
      ph: 7.0,
    },
  },
  {
    id: 'cesio',
    name: 'Cesio',
    symbol: 'Cs',
    atomicNumber: 55,
    formula: 'Cs',
    isCompound: false,
    category: 'Alcalinos',
    state: 'Líquido',
    color: '#eab308',
    accentColor: '#ca8a04',
    avatarEmoji: '🐉',
    visualDescription: 'Dragón serpentino dorado líquido que desprende ondas de choque térmicas continuas.',
    lore: 'Enemigo formidable del Capítulo 5. Sus ondas de choque explosivas forzaron a Leo y Yan a sintetizar Óxido de Magnesio.',
    reactionHistory: 'Capítulo 5. El metal más reactivo y pirofórico de la naturaleza.',
    property: {
      name: 'Ondas de Choque Pirofóricas',
      description: 'Genera explosiones consecutivas ignorando 20 puntos de resistencia física.',
      effectCode: 'HIDRORREACCION',
    },
    stats: {
      hp: 193,
      maxHp: 193,
      fuerza: 60,
      resistencia: 20,
      velocidad: 90,
      poderEspecial: 14,
      masaAtomica: 132.905,
      durezaMohs: 0.2,
      puntoFusionC: 28.5,
      electronegatividad: 0.79,
      ph: 14.0,
    },
  },
  {
    id: 'bario',
    name: 'Bario',
    symbol: 'Ba',
    atomicNumber: 56,
    formula: 'Ba',
    isCompound: false,
    category: 'Alcalinotérreos',
    state: 'Sólido',
    color: '#94a3b8',
    accentColor: '#64748b',
    avatarEmoji: '🗿',
    visualDescription: 'Gólem rocoso pesado de baritina color gris perla con puños monolíticos.',
    lore: 'Utilizado por alumnos acosadores en el Capítulo 8 antes de que Ana lo venciera con Ferrosilicio.',
    reactionHistory: 'Capítulo 8. Capaz de sintetizarse en el impenetrable Sulfato de Bario.',
    property: {
      name: 'Pesadez Alcalina',
      description: 'Neutralizador de campos de Oxidación Ambiental.',
      effectCode: 'ELASTICO',
    },
    stats: {
      hp: 197,
      maxHp: 197,
      fuerza: 65,
      resistencia: 75,
      velocidad: 9,
      poderEspecial: 11,
      masaAtomica: 137.327,
      durezaMohs: 1.25,
      puntoFusionC: 727,
      electronegatividad: 0.89,
      ph: 11.0,
    },
  },
  {
    id: 'magnesio',
    name: 'Magnesio',
    symbol: 'Mg',
    atomicNumber: 12,
    formula: 'Mg',
    isCompound: false,
    category: 'Alcalinotérreos',
    state: 'Sólido',
    color: '#e2e8f0',
    accentColor: '#cbd5e1',
    avatarEmoji: '⚡',
    visualDescription: 'Guerrero titánico acorazado de cristales blancos incandescentes que emite un destello cegador.',
    lore: 'Encontrado en los huertos del Capítulo 4 y usado como pieza clave en el hospital del Capítulo 5.',
    reactionHistory: 'Capítulo 4, 5. Desprende luz blanca deslumbrante al reaccionar.',
    property: {
      name: 'Destello Refractario',
      description: 'Ciega temporalmente al atacante reduciendo su velocidad en 15.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 54,
      maxHp: 54,
      fuerza: 55,
      resistencia: 60,
      velocidad: 31,
      poderEspecial: 10,
      masaAtomica: 24.305,
      durezaMohs: 2.5,
      puntoFusionC: 650,
      electronegatividad: 1.31,
      ph: 10.0,
    },
  },
  {
    id: 'cobre',
    name: 'Cobre',
    symbol: 'Cu',
    atomicNumber: 29,
    formula: 'Cu',
    isCompound: false,
    category: 'Metales de Transición',
    state: 'Sólido',
    color: '#b45309',
    accentColor: '#78350f',
    avatarEmoji: '🐂',
    visualDescription: 'Minotauro cuadrúpedo de coraza de cobre rojizo bruñido y cuernos trenzados conductores.',
    lore: 'Provee la red eléctrica del hospital en el Capítulo 5 y protagoniza la reparación del puente con enlace metálico en el Capítulo 6.',
    reactionHistory: 'Capítulo 5, 6, 10. Clave en el estudio del mar de electrones.',
    property: {
      name: 'Mar de Electrones',
      description: 'Conducción perfecta de energía. Reduce daño recibido de tipo Plasma un 50%.',
      effectCode: 'CONDUCTOR',
    },
    stats: {
      hp: 114,
      maxHp: 114,
      fuerza: 68,
      resistencia: 72,
      velocidad: 19,
      poderEspecial: 7,
      masaAtomica: 63.546,
      durezaMohs: 3.0,
      puntoFusionC: 1084.62,
      electronegatividad: 1.90,
      ph: 7.0,
    },
  },
  {
    id: 'oxigeno',
    name: 'Oxígeno',
    symbol: 'O',
    atomicNumber: 8,
    formula: 'O',
    isCompound: false,
    category: 'No Metales',
    state: 'Gaseoso',
    color: '#ef4444',
    accentColor: '#b91c1c',
    avatarEmoji: '🐱',
    visualDescription: 'Felino lémur ágil con cola flameante y garras de combustión oxidante.',
    lore: 'Nacido en los santuarios boscosos por fotosíntesis en el Capítulo 3. El gran alimentador del fuego elemental.',
    reactionHistory: 'Capítulo 3, 4, 6, 9. Vital para la vida y para las reacciones redox.',
    property: {
      name: 'Comburente Voraz',
      description: 'Aplica el estado de Combustión aumentando el daño de ataques térmicos en +20.',
      effectCode: 'OXIDANTE',
    },
    stats: {
      hp: 46,
      maxHp: 46,
      fuerza: 50,
      resistencia: 20,
      velocidad: 34,
      poderEspecial: 7,
      masaAtomica: 15.999,
      puntoFusionC: -218.79,
      electronegatividad: 3.44,
      ph: 7.0,
    },
  },
  {
    id: 'estano',
    name: 'Estaño',
    symbol: 'Sn',
    atomicNumber: 50,
    formula: 'Sn',
    isCompound: false,
    category: 'Metales del Bloque p',
    state: 'Sólido',
    color: '#64748b',
    accentColor: '#475569',
    avatarEmoji: '🐐',
    visualDescription: 'Cabra mística de pelaje plateado metálico y cuernos de soldadura dúctil.',
    lore: 'Rescatado de la Casiterita en el lecho del río en el Capítulo 6 para soldar los cables de cobre del puente.',
    reactionHistory: 'Capítulo 6, 10. Forma aleaciones legendarias como el Bronce.',
    property: {
      name: 'Ductilidad de Soldadura',
      description: 'Permite reparar 25 PV de una criatura aliada al realizar una síntesis.',
      effectCode: 'ELASTICO',
    },
    stats: {
      hp: 179,
      maxHp: 179,
      fuerza: 55,
      resistencia: 60,
      velocidad: 20,
      poderEspecial: 7,
      masaAtomica: 118.710,
      durezaMohs: 1.5,
      puntoFusionC: 231.93,
      electronegatividad: 1.96,
      ph: 7.0,
    },
  },
  {
    id: 'cloro',
    name: 'Cloro',
    symbol: 'Cl',
    atomicNumber: 17,
    formula: 'Cl',
    isCompound: false,
    category: 'Halógenos',
    state: 'Gaseoso',
    color: '#84cc16',
    accentColor: '#4d7c0f',
    avatarEmoji: '🦅',
    visualDescription: 'Ave majestuosa de plumas verde-lima que emana nubes halógenas corrosivas y purificadoras.',
    lore: 'Usado en el Capítulo 7 para apaciguar al Sodio y en el Capítulo 8 para coagular sedimentos fluviales.',
    reactionHistory: 'Capítulo 7, 8. Gran afinidad para capturar electrones y formar sales.',
    property: {
      name: 'Plasma Térmico / Halógeno',
      description: 'Activa el campo Plasma Térmico restando 20 de Vida por turno a rivales no alcalinos.',
      effectCode: 'CORROSIVO',
    },
    stats: {
      hp: 65,
      maxHp: 65,
      fuerza: 60,
      resistencia: 30,
      velocidad: 32,
      poderEspecial: 2, // Muy ácido / oxidante
      masaAtomica: 35.45,
      puntoFusionC: -101.5,
      electronegatividad: 3.16,
      ph: 2.0,
    },
  },
  {
    id: 'calcio',
    name: 'Calcio',
    symbol: 'Ca',
    atomicNumber: 20,
    formula: 'Ca',
    isCompound: false,
    category: 'Alcalinotérreos',
    state: 'Sólido',
    color: '#f8fafc',
    accentColor: '#94a3b8',
    avatarEmoji: '🦏',
    visualDescription: 'Colosal rinoceronte blanco con coraza ósea calcificada y cuernos de carbonato impenetrable.',
    lore: 'El fiel protector del granero en el Capítulo 7 y el escudo invocado por todo el equipo en el Capítulo 9 contra el ácido fluorhídrico.',
    reactionHistory: 'Capítulo 7, 9, 10. El pilar estructural de las defensas biológicas y geológicas.',
    property: {
      name: 'Muro Estructural Óseo',
      description: 'Soporta hasta 2 impactos críticos absorbiendo la fuerza cinética sin sufrir retroceso.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 90,
      maxHp: 90,
      fuerza: 62,
      resistencia: 88,
      velocidad: 10,
      poderEspecial: 11,
      masaAtomica: 40.078,
      durezaMohs: 1.75,
      puntoFusionC: 842,
      electronegatividad: 1.00,
      ph: 11.0,
    },
  },

  // --- COMPUESTOS Y MOLÉCULAS DE LA SERIE ---
  {
    id: 'agua',
    name: 'Agua',
    symbol: 'H₂O',
    formula: 'H2O',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Líquido',
    color: '#0284c7',
    accentColor: '#0369a1',
    avatarEmoji: '💧',
    visualDescription: 'Criatura etérea bicéfala de dos esferas de hidrógeno unidas a un orbe central de oxígeno con zarcillos fluidos.',
    lore: 'Formada por Leo en el bosque del Capítulo 3 y base universal de todas las soluciones del mundo de Materia.',
    reactionHistory: 'Capítulo 3, 4. Solvente de la vida y moderador térmico.',
    composition: [
      { elementId: 'hidrogeno', count: 2 },
      { elementId: 'oxigeno', count: 1 },
    ],
    property: {
      name: 'Solvente Universal',
      description: 'Limpia automáticamente el debuff de Corrosión y equilibra el pH a 7.',
      effectCode: 'ELASTICO',
    },
    stats: {
      hp: 68,
      maxHp: 68,
      fuerza: 40,
      resistencia: 60,
      velocidad: 28,
      poderEspecial: 7,
      masaAtomica: 18.015,
      puntoFusionC: 0,
      ph: 7.0,
    },
  },
  {
    id: 'co2',
    name: 'Dióxido de Carbono',
    symbol: 'CO₂',
    formula: 'CO2',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Gaseoso',
    color: '#64748b',
    accentColor: '#334155',
    avatarEmoji: '💨',
    visualDescription: 'Espíritu gaseoso alado con tentáculos de niebla densa que asfixia cualquier llama circundante.',
    lore: 'Invocado magistralmente por Yan en el Capítulo 3 para apagar las llamas del bosque sin generar humo asfixiante.',
    reactionHistory: 'Capítulo 3, 4. Extintor elemental por excelencia.',
    composition: [
      { elementId: 'carbono', count: 1 },
      { elementId: 'oxigeno', count: 2 },
    ],
    property: {
      name: 'Asfixia Ígnea',
      description: 'Anula por completo todos los ataques y efectos de tipo Combustión durante 2 turnos.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 74,
      maxHp: 74,
      fuerza: 48,
      resistencia: 45,
      velocidad: 30,
      poderEspecial: 5,
      masaAtomica: 44.01,
      ph: 5.5,
    },
  },
  {
    id: 'sic_abrasor',
    name: 'Carburo de Silicio (SiC)',
    symbol: 'SiC',
    formula: 'SiC',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#0f172a',
    accentColor: '#38bdf8',
    avatarEmoji: '⚙️',
    visualDescription: 'Titán negro balístico blindado con sierras circulares de diamante industrial y blindaje cerámico balístico.',
    lore: 'Creado por Yan en el Capítulo 10 en su momento cumbre para aniquilar brutalmente al Gólem de Bronce del Sindicato Isótopo.',
    reactionHistory: 'Capítulo 10. Dureza 9.5 en la escala de Mohs, casi equiparable al diamante.',
    composition: [
      { elementId: 'silicio', count: 1 },
      { elementId: 'carbono', count: 1 },
    ],
    property: {
      name: 'Abrasión Balística Extrema',
      description: 'Ignora el 50% de la Resistencia física del rival y no puede sufrir daño por rebote (recoil).',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 100,
      maxHp: 100,
      fuerza: 95,
      resistencia: 96,
      velocidad: 22,
      poderEspecial: 7,
      masaAtomica: 40.096,
      durezaMohs: 9.5,
      puntoFusionC: 2730,
      ph: 7.0,
    },
  },
  {
    id: 'nacl',
    name: 'Cloruro de Sodio (Sal Común)',
    symbol: 'NaCl',
    formula: 'NaCl',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#f1f5f9',
    accentColor: '#94a3b8',
    avatarEmoji: '🐻',
    visualDescription: 'Oso polar acorazado con cristales cúbicos de halita y un orbe de salazón reflectante en la cola.',
    lore: 'El resultado de neutralizar la furia reactiva del Sodio con Cloro en el sistema de riego del Capítulo 7.',
    reactionHistory: 'Capítulo 7. Enlace iónico clásico perfecto.',
    composition: [
      { elementId: 'sodio', count: 1 },
      { elementId: 'cloro', count: 1 },
    ],
    property: {
      name: 'Estabilidad Cúbica Iónica',
      description: 'Inmune a debuffs de tipo Disolución y reduce en un 30% el daño elemental recibido.',
      effectCode: 'ELASTICO',
    },
    stats: {
      hp: 118,
      maxHp: 118,
      fuerza: 62,
      resistencia: 74,
      velocidad: 45,
      poderEspecial: 7,
      masaAtomica: 58.44,
      durezaMohs: 2.5,
      puntoFusionC: 801,
      ph: 7.0,
    },
  },
  {
    id: 'oxido_magnesio',
    name: 'Óxido de Magnesio (MgO)',
    symbol: 'MgO',
    formula: 'MgO',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#f8fafc',
    accentColor: '#e2e8f0',
    avatarEmoji: '🐱',
    visualDescription: 'Gatito blanco con orejas de zorro alquímico que sostiene un mortero de polvo cerámico refractario.',
    lore: 'Sintetizado por Leo y Yan en el Capítulo 5 para absorber las ondas de choque del Cesio en el hospital veterinario.',
    reactionHistory: 'Capítulo 5. Material refractario con punto de fusión de 2852 °C.',
    composition: [
      { elementId: 'magnesio', count: 1 },
      { elementId: 'oxigeno', count: 1 },
    ],
    property: {
      name: 'Escudo Cerámico Refractario',
      description: 'Absorbe explosiones y ataques térmicos reduciendo su daño a tan solo 5 PV.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 90,
      maxHp: 90,
      fuerza: 60,
      resistencia: 92,
      velocidad: 25,
      poderEspecial: 10,
      masaAtomica: 40.304,
      puntoFusionC: 2852,
      ph: 10.3,
    },
  },
  {
    id: 'carbonato_calcio',
    name: 'Carbonato Cálcico',
    symbol: 'CaCO₃',
    formula: 'CaCO3',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#fed7aa',
    accentColor: '#f97316',
    avatarEmoji: '🐚',
    visualDescription: 'Criatura coralina marina con conchas y perlas calcáreas que neutraliza instantáneamente los ácidos.',
    lore: 'Invocado por Yan en el Capítulo 10 para neutralizar la temible acidez del Ácido Sulfúrico del Sindicato Isótopo.',
    reactionHistory: 'Capítulo 10. El gran neutralizador geoquímico.',
    composition: [
      { elementId: 'calcio', count: 1 },
      { elementId: 'carbono', count: 1 },
      { elementId: 'oxigeno', count: 3 },
    ],
    property: {
      name: 'Neutralización Ácida',
      description: 'Cura permanentemente el estado de Corrosión de todo el equipo y restaura 30 PV.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 150,
      maxHp: 150,
      fuerza: 55,
      resistencia: 82,
      velocidad: 18,
      poderEspecial: 9,
      masaAtomica: 100.086,
      ph: 9.4,
    },
  },
  {
    id: 'bronce',
    name: 'Gólem de Bronce (CuSn)',
    symbol: 'CuSn',
    formula: 'CuSn',
    isCompound: true,
    category: 'Aleación',
    state: 'Sólido',
    color: '#b45309',
    accentColor: '#78350f',
    avatarEmoji: '🛡️',
    visualDescription: 'Colosal gólem antiguo forjado con bloques de cobre y estaño, con hombreras de engranaje masivas.',
    lore: 'La bestia invasora enviada por el Sindicato Isótopo en el Capítulo 10 para custodiar la mina y contaminar el río.',
    reactionHistory: 'Capítulo 10. Destruido por el Carburo de Silicio de Yan.',
    composition: [
      { elementId: 'cobre', count: 1 },
      { elementId: 'estano', count: 1 },
    ],
    property: {
      name: 'Aleación Milenaria',
      description: 'Reduce el daño de impacto de los sólidos en 25 puntos.',
      effectCode: 'MAGNETICO',
    },
    stats: {
      hp: 242,
      maxHp: 242,
      fuerza: 82,
      resistencia: 88,
      velocidad: 14,
      poderEspecial: 7,
      masaAtomica: 182.256,
      durezaMohs: 3.5,
      ph: 7.0,
    },
  },
  {
    id: 'acido_sulfurico',
    name: 'Ácido Sulfúrico',
    symbol: 'H₂SO₄',
    formula: 'H2SO4',
    isCompound: true,
    category: 'Ácido / Base',
    state: 'Líquido',
    color: '#84cc16',
    accentColor: '#15803d',
    avatarEmoji: '🧪',
    visualDescription: 'Monstruo viscoso verde esmeralda con garras sulfurosas que gotean ácido disolvente.',
    lore: 'El arma de veneno y corrosión utilizada por el Sindicato Isótopo en el Capítulo 10 en la vieja explotación minera.',
    reactionHistory: 'Capítulo 10. Capaz de desintegrar rocas y estructuras.',
    composition: [
      { elementId: 'hidrogeno', count: 2 },
      { elementId: 'oxigeno', count: 4 },
    ],
    property: {
      name: 'Corrosión Extrema',
      description: 'Aplica el estado de Corrosión al enemigo restando 15% de Resistencia por turno de forma permanente.',
      effectCode: 'CORROSIVO',
    },
    stats: {
      hp: 148,
      maxHp: 148,
      fuerza: 72,
      resistencia: 45,
      velocidad: 26,
      poderEspecial: 0.5, // Extremadamente ácido
      masaAtomica: 98.079,
      ph: 0.5,
    },
  },
  {
    id: 'ferrosilicio',
    name: 'Ferrosilicio (FeSi)',
    symbol: 'FeSi',
    formula: 'FeSi',
    isCompound: true,
    category: 'Aleación',
    state: 'Sólido',
    color: '#475569',
    accentColor: '#1e293b',
    avatarEmoji: '🪨',
    visualDescription: 'Gólem titán acorazado con crestas afiladas de silicio metálico incrustadas en un chasis de hierro.',
    lore: 'Sintetizado por Ana y Kai en el Capítulo 8 para derrotar al Sulfato de Bario y en el Capítulo 10 para frenar al Gólem de Bronce.',
    reactionHistory: 'Capítulo 8, 10. Gran resistencia a la abrasión y a la desoxidación.',
    composition: [
      { elementId: 'hierro', count: 1 },
      { elementId: 'silicio', count: 1 },
    ],
    property: {
      name: 'Desoxidación Estructural',
      description: 'Aumenta la fuerza en +20 contra metales pesados.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 134,
      maxHp: 134,
      fuerza: 85,
      resistencia: 86,
      velocidad: 16,
      poderEspecial: 7,
      masaAtomica: 83.93,
      durezaMohs: 6.5,
      puntoFusionC: 1410,
      ph: 7.0,
    },
  },
  {
    id: 'silice_arena',
    name: 'Sílice / Arena',
    symbol: 'SiO₂',
    formula: 'SiO2',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#eab308',
    accentColor: '#a16207',
    avatarEmoji: '⏳',
    visualDescription: 'Pequeño muñeco de arena dorada que se dispersa en una red de dunas y filtros cristalinos.',
    lore: 'Conjurado por Kai en el Capítulo 9 para crear una red de filtrado y purificar las aguas del gran río de Materia.',
    reactionHistory: 'Capítulo 9, 10. Filtro natural por excelencia.',
    composition: [
      { elementId: 'silicio', count: 1 },
      { elementId: 'oxigeno', count: 2 },
    ],
    property: {
      name: 'Red de Filtrado',
      description: 'Filtra y absorbe sedimentos y partículas en suspensión reduciendo el daño a distancia.',
      effectCode: 'ELASTICO',
    },
    stats: {
      hp: 90,
      maxHp: 90,
      fuerza: 45,
      resistencia: 80,
      velocidad: 20,
      poderEspecial: 7,
      masaAtomica: 60.084,
      durezaMohs: 7.0,
      puntoFusionC: 1713,
      ph: 7.0,
    },
  },
  {
    id: 'fosfuro_hierro',
    name: 'Fosfuro de Hierro (Fe3P)',
    symbol: 'Fe₃P',
    formula: 'Fe3P',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#57534e',
    accentColor: '#292524',
    avatarEmoji: '🦖',
    visualDescription: 'Dinosaurio acorazado con placas de hierro dentadas y espinas de fósforo mineral refractario.',
    lore: 'Creado por Ana y Yan en el Capítulo 3 para derrotar al Trióxido de Dimanganeso de los incendiarios.',
    reactionHistory: 'Capítulo 3. Combinación táctica entre el Hierro de Ana y el Fósforo de Yan.',
    composition: [
      { elementId: 'hierro', count: 3 },
      { elementId: 'fosforo', count: 1 },
    ],
    property: {
      name: 'Placas Dentadas',
      description: 'Aplica el efecto Lacerante causando 20 pts de daño adicional al caer derrotado.',
      effectCode: 'LACERANTE',
    },
    stats: {
      hp: 198,
      maxHp: 198,
      fuerza: 88,
      resistencia: 76,
      velocidad: 18,
      poderEspecial: 7,
      masaAtomica: 198.51,
      durezaMohs: 6.0,
      ph: 7.0,
    },
  },
  {
    id: 'sulfato_bario',
    name: 'Sulfato de Bario (BaSO4)',
    symbol: 'BaSO₄',
    formula: 'BaSO4',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#e2e8f0',
    accentColor: '#94a3b8',
    avatarEmoji: '🦔',
    visualDescription: 'Ardilla polar albina con cola esponjosa de nubes minerales y un escudo denso radiopaco.',
    lore: 'Utilizado por el estudiante rival en el Capítulo 8 para superar temporalmente al Hierro de Ana.',
    reactionHistory: 'Capítulo 8. Insoluble en agua y con enorme densidad radiopaca.',
    composition: [
      { elementId: 'bario', count: 1 },
      { elementId: 'oxigeno', count: 4 },
    ],
    property: {
      name: 'Blindaje Radiopaco Insoluble',
      description: 'Inmune a debuffs de tipo Disolución y reduce en 50% el daño recibido por ataques ácidos.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 283,
      maxHp: 283,
      fuerza: 52,
      resistencia: 94,
      velocidad: 12,
      poderEspecial: 7,
      masaAtomica: 233.39,
      ph: 7.0,
    },
  },
  {
    id: 'cloruro_hierro',
    name: 'Cloruro de Hierro (FeCl3)',
    symbol: 'FeCl₃',
    formula: 'FeCl3',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#78350f',
    accentColor: '#451a03',
    avatarEmoji: '🦀',
    visualDescription: 'Cangrejo mecánico de pinzas férreas cubiertas de fango químico con capacidad de coagulación.',
    lore: 'Sintetizado por los niños del río en el Capítulo 8 para hacer precipitar los sedimentos y limpiar el cauce.',
    reactionHistory: 'Capítulo 8. Coagulante y floculante en el tratamiento de aguas.',
    composition: [
      { elementId: 'hierro', count: 1 },
      { elementId: 'cloro', count: 3 },
    ],
    property: {
      name: 'Floculación y Coagulación',
      description: 'Atrapa y reduce la velocidad de todos los enemigos en 20 puntos durante 2 turnos.',
      effectCode: 'CORROSIVO',
    },
    stats: {
      hp: 162,
      maxHp: 162,
      fuerza: 68,
      resistencia: 58,
      velocidad: 20,
      poderEspecial: 2.5,
      masaAtomica: 162.2,
      ph: 2.5,
    },
  },
  {
    id: 'carbonato_magnesio',
    name: 'Carbonato de Magnesio',
    symbol: 'MgCO₃',
    formula: 'MgCO3',
    isCompound: true,
    category: 'Compuesto Molecular',
    state: 'Sólido',
    color: '#e0f2fe',
    accentColor: '#7dd3fc',
    avatarEmoji: '🐉',
    visualDescription: 'Dragón wyrm serpentino blanco de cristales subterráneos que compacta el suelo del huerto.',
    lore: 'El intruso subterráneo del Capítulo 4 que volvía infértil el huerto del joven agricultor antes de ser estabilizado por Leo.',
    reactionHistory: 'Capítulo 4. MgCO3 + 2H -> H2O + Mg + CO2.',
    composition: [
      { elementId: 'magnesio', count: 1 },
      { elementId: 'carbono', count: 1 },
      { elementId: 'oxigeno', count: 3 },
    ],
    property: {
      name: 'Compactación Mineral',
      description: 'Aumenta su propia Resistencia en +15 al absorber la fuerza del impacto enemigo.',
      effectCode: 'REFRACTARIO',
    },
    stats: {
      hp: 134,
      maxHp: 134,
      fuerza: 62,
      resistencia: 78,
      velocidad: 21,
      poderEspecial: 9,
      masaAtomica: 84.314,
      ph: 9.5,
    },
  }
];

// --- PERSONAJES DE LA BIBLIA DE PRODUCCIÓN ---
export const CHARACTERS: CharacterProfile[] = [
  // PROTAGONISTAS
  {
    id: 'leo',
    name: 'Leo',
    age: 16,
    role: 'Protagonista',
    category: 'protagonista',
    costCoins: 50,
    archetype: 'Líder optimista e intuitivo',
    catchphrase: '¡¡Reaccionemos al mundo!!',
    concept: 'Joven optimista enamorado del mundo que le rodea y de los procesos de la naturaleza.',
    visual: 'Chico joven de cabello naranja rebelde y ojos azules vivos. Viste chaleco de explorador vibrante, camiseta azul, pantalones cortos y botas de tracción.',
    palette: ['#f97316', '#3b82f6', '#eab308'],
    signatureGadget: 'Mendelomnio de muñeca con interfaz circular holográfica.',
    starterElementId: 'hidrogeno',
    motivation: 'Quiere ser el mejor maestro elemental de la Academia y encontrar pistas sobre el destino de su padre desaparecido.',
    weakness: 'Impulsivo y descuidado; teme dañar a quienes le rodean.',
    evolutionArc: 'Pasa de resolver problemas por azar e intuición infantil a diseñar estrategias racionales y dar un cambio maduro ante el peligro real.',
    avatar: '👦'
  },
  {
    id: 'kai',
    name: 'Kai',
    age: 16,
    role: 'Coprotagonista / Estratega',
    category: 'protagonista',
    costCoins: 50,
    archetype: 'Fuente inagotable de conocimiento',
    catchphrase: '¡Analicemos este momento!',
    concept: 'Joven con descomunal caudal de conocimientos químicos y ansia inagotable por investigar.',
    visual: 'Chico moreno de complexión delgada, vestido con tejanos oscuros y chaquetilla técnica azul marina. Siempre se sube las gafas con un dedo antes de invocar.',
    palette: ['#1e3a8a', '#f8fafc', '#94a3b8'],
    signatureGadget: 'Gafas de marco fino que integran un Mendelomnio con visor HUD de datos.',
    starterElementId: 'silicio',
    motivation: 'Demostrar que es digno a ojos de sus padres, ambos reputados catedráticos de la Academia.',
    weakness: 'Quedarse sin opciones lógicas o no alcanzar los conocimientos que requiera una situación crítica.',
    evolutionArc: 'Empieza seguro e ilustrado hasta recibir un golpe de realidad que le abre los ojos y le convierte en un estratega más modesto y empático.',
    avatar: '🧑‍🔬'
  },
  {
    id: 'ana',
    name: 'Ana',
    age: 16,
    role: 'Coprotagonista / Baluarte',
    category: 'protagonista',
    costCoins: 50,
    archetype: 'Secundaria valiente y con iniciativa',
    catchphrase: '¡Se acabó! ¡Dejadme a mí!',
    concept: 'Joven empoderada, autosuficiente y de gran fortaleza física y mental.',
    visual: 'Chica atractiva y atlética con cabello cobrizo y ojos almendra. Viste chaleco de cuero con hombreras, guantes sin dedos, pantalones de montaña y botas robustas.',
    palette: ['#b45309', '#78350f', '#475569'],
    signatureGadget: 'Mendelomnio antiguo de herencia familiar que lleva colgado al pecho sobre su chaleco.',
    starterElementId: 'hierro',
    motivation: 'Es la mayor de 5 hermanos de familia humilde; desea graduarse en un puesto de élite para sostener económicamente a su familia.',
    weakness: 'Miedo al fracaso y a la mediocridad; a veces peca de individualista.',
    evolutionArc: 'Comienza retraída y desconfiada hasta abrir su corazón emocional al equipo y liderar la defensa colectiva.',
    avatar: '👩‍🔧'
  },
  {
    id: 'yan',
    name: 'Yan',
    age: 16,
    role: 'Coprotagonista / Antihéroe Rival',
    category: 'protagonista',
    costCoins: 75,
    archetype: 'Rival prodigio solitario y antihéroe',
    catchphrase: 'Aparta bufón.',
    concept: 'Joven prodigio brillante, soberbio, frío e implacable en el cálculo químico.',
    visual: 'Joven alto de pelo negro azabache y mirada penetrante. Viste de negro con ropa oscura de explorador y una gran gabardina negra de campo.',
    palette: ['#0f172a', '#581c87', '#881337'],
    signatureGadget: 'Brazalete Mendelomnio en el interior de su muñeca con activador en el pendiente.',
    starterElementId: 'carbono',
    motivation: 'Búsqueda del poder absoluto y autosuficiencia sin depender de nadie.',
    weakness: 'Incapacidad para empatizar; su prepotencia lo aísla del resto del mundo.',
    evolutionArc: 'Poco a poco siente hastío por el trabajo en equipo hasta estallar en rabia en la cantera (Capítulo 10), invocando dos elementos a la vez antes de romper con el grupo.',
    avatar: '🧥'
  },
  {
    id: 'prof_lantan',
    name: 'Prof. Lantan',
    age: 60,
    role: 'Mentor de la Academia',
    category: 'protagonista',
    costCoins: 80,
    archetype: 'Mentor excéntrico y científico olvidadizo',
    catchphrase: '¡Cualquier hora es buena para aprender algo nuevo!',
    concept: 'Profesor excéntrico, inventor genial en sus ratos libres y guía paternalista de la nueva generación.',
    visual: 'Señor mayor de pelo y barba alborotada (a veces humeante por explosiones de laboratorio), jerséis de cuadros, pantalones de pana y bata manchada repleta de notas.',
    palette: ['#f8fafc', '#15803d', '#78350f'],
    signatureGadget: 'Mendelomnio biomecánico experimental autoimplantado directamente en la palma de su mano.',
    starterElementId: 'magnesio',
    motivation: 'Vocación absoluta por transmitir la belleza de la química y formar a los futuros Campeones Elementales.',
    weakness: 'Olvidadizo y patoso; a veces arriesga demasiado en sus experimentos.',
    evolutionArc: 'Tras su apariencia distraída, revela al final de la temporada que formó el equipo intencionadamente con un propósito crucial vinculado al padre de Leo.',
    avatar: '👨‍🏫'
  },

  // PERSONAJES SECUNDARIOS
  {
    id: 'rectora_mendeleva',
    name: 'Rectora Mendeleva',
    age: 54,
    role: 'Directora de la Academia de Materia',
    category: 'secundario',
    costCoins: 90,
    archetype: 'Custodia suprema del Orden Periódico',
    catchphrase: 'La materia nunca se destruye; el honor tampoco.',
    concept: 'Máxima autoridad académica de Nobelia, descendiente del linaje de los Grandes Formuladores.',
    visual: 'Mujer distinguida con túnica ceremonial azul cobalto, gafas prismáticas de cuarzo y porte aristocrático imponente.',
    palette: ['#1e1b4b', '#3b82f6', '#fbbf24'],
    signatureGadget: 'Cetro Mendelomnio de Resonancia Magnética Cuántica.',
    starterElementId: 'calcio',
    motivation: 'Preservar el equilibrio de la tabla periódica y evitar que el Sindicato desestabilice los núcleos de Materia.',
    weakness: 'Burocrática y reticente a los métodos no canónicos.',
    evolutionArc: 'Comienza dudando del grupo rebelde de Leo pero termina nombrándolos escuadrón de intervención especial.',
    avatar: '👩‍💼'
  },
  {
    id: 'denis_tecnico',
    name: 'Denis el Técnico',
    age: 22,
    role: 'Maestro Forjador & Cristalógrafo',
    category: 'secundario',
    costCoins: 45,
    archetype: 'Especialista en redes cristalinas y aleaciones',
    catchphrase: 'Si tiene enlace metálico, tiene arreglo.',
    concept: 'Joven mecánico de reactores que suministra reactivos y repara los marcos de los Mendelomnios rotos.',
    visual: 'Mono de trabajo cubierto de grasa con herramientas neumáticas, guantes térmicos ignífugos y bandana protectora.',
    palette: ['#451a03', '#ea580c', '#71717a'],
    signatureGadget: 'Soplete de Plasma con analizador de redes de Bravais.',
    starterElementId: 'cobre',
    motivation: 'Construir la aleación más resistente y ligera jamás sintetizada en la historia de Nobelia.',
    weakness: 'Imprudente con las presiones de gas en espacios cerrados.',
    evolutionArc: 'Provee mejoras cruciales a la Mesa de Síntesis durante los momentos más oscuros de la campaña.',
    avatar: '👨‍🏭'
  },
  {
    id: 'elena_botanica',
    name: 'Elena',
    age: 17,
    role: 'Estudiante de Bioquímica y Botánica',
    category: 'secundario',
    costCoins: 45,
    archetype: 'Ecologista y botánica analítica',
    catchphrase: 'Las plantas ya hacían química antes que nosotros.',
    concept: 'Estudiante brillante apasionada por la fotosíntesis, el ciclo del nitrógeno y los bioelementos orgánicos.',
    visual: 'Chica con trenza lateral, guardapolvo verde esmeralda y sensores bioluminiscentes en la solapa.',
    palette: ['#064e3b', '#10b981', '#a7f3d0'],
    signatureGadget: 'Mendelomnio Botánico con cápsulas de esporas y fluidos clorofílicos.',
    starterElementId: 'oxigeno',
    motivation: 'Restaurar los bosques quemados por el Sindicato Isótopo mediante síntesis de fertilizantes minerales.',
    weakness: 'Rechaza la violencia y duda en combates destructivos.',
    evolutionArc: 'Aprende a usar la química defensiva para blindar ecosistemas enteros.',
    avatar: '👩‍🌾'
  },
  {
    id: 'maestro_dalton',
    name: 'Maestro Dalton',
    age: 72,
    role: 'Decano Emérito de la Teoría Atómica',
    category: 'secundario',
    costCoins: 70,
    archetype: 'Erudito veterano de las Guerras Moleculares',
    catchphrase: 'Los átomos son indivisibles en el alma.',
    concept: 'Histórico veterano que presenció los primeros experimentos de ruptura nuclear antes de retirarse a los archivos.',
    visual: 'Anciano con gabán de terciopelo verde musgo, monóculo de aumento atómico y libro de bitácora encuadernado en cuero.',
    palette: ['#14532d', '#78350f', '#e2e8f0'],
    signatureGadget: 'Bastón Mendelomnio de madera fosilizada con núcleo de uraninita sellada.',
    starterElementId: 'fosforo',
    motivation: 'Documentar todas las especies de Elementbeasts antes de que el mundo olvide la química pura.',
    weakness: 'Movilidad reducida y nostalgia del pasado.',
    evolutionArc: 'Custodia los rollos secretos sobre el origen del Mendelomnio que busca el padre de Leo.',
    avatar: '🧙‍♂️'
  },

  // SINDICATO ISÓTOPO (ANTAGONISTAS / CENSURADOS)
  {
    id: 'meitner',
    name: 'Meitner',
    age: 38,
    role: 'Comandante Supremo del Sindicato Isótopo',
    category: 'sindicato',
    costCoins: 120,
    isCensored: true,
    archetype: 'Líder criminal calculador y frío',
    catchphrase: 'Control isn\'t given. It\'s isotopic.',
    concept: 'Comandante supremo del Sindicato Isótopo, organización que busca manipular isótopos inestables y forzar la antimateria.',
    visual: 'Imponente líder con abrigo táctico blindado borgoña oscuro, visores cian y guantelete de captura de isótopos radiactivos.',
    palette: ['#0f172a', '#701a75', '#06b6d4'],
    signatureGadget: 'Dispositivo Isótopo Multi-función y Proyector Holográfico Táctico.',
    starterElementId: 'acido_sulfurico',
    motivation: 'Completar la tabla periódica con isótopos artificiales y desatar la energía de enlace mundial.',
    weakness: 'Arrogancia extrema y desprecio por los enlaces iónicos de baja energía.',
    evolutionArc: 'Opera en las sombras a través de agentes uniformados y monstruos químicos hasta revelar su plan en la alta montaña.',
    avatar: '🦹‍♂️'
  },
  {
    id: 'dra_plutonia',
    name: 'Dra. Plutonia',
    age: 35,
    role: 'Científica Renegada de Fisión',
    category: 'sindicato',
    costCoins: 100,
    isCensored: true,
    archetype: 'Científica radical y obsesiva',
    catchphrase: 'La masa perdida es poder absoluto.',
    concept: 'Antigua investigadora de la Academia expulsada por experimentos ilegales de transmutación nuclear.',
    visual: 'Bata negra reforzada con plomo, máscara con filtro de radiación y mechones de pelo teñidos de amarillo flúor.',
    palette: ['#020617', '#854d0e', '#facc15'],
    signatureGadget: 'Inyector de Neutrones Térmicos de aceleración angular.',
    starterElementId: 'cesio',
    motivation: 'Romper la barrera de Coulomb para crear el elemento 119 con masa crítica ilimitada.',
    weakness: 'Inestabilidad emocional cuando sus reacciones sufren desaceleración.',
    evolutionArc: 'Desata el Gólem de Bronce y los ataques de corrosión en la cantera abandonada.',
    avatar: '🦹‍♀️'
  },
  {
    id: 'corrosor_alfa',
    name: 'Corrosor Alfa',
    age: 29,
    role: 'Ejecutor de Ácidos & Ataques de Campo',
    category: 'sindicato',
    costCoins: 85,
    isCensored: true,
    archetype: 'Mercenario demoledor de pH extremo',
    catchphrase: 'Todo lo que brilla puede ser disuelto.',
    concept: 'Especialista en demolición táctica que utiliza soluciones de pH cero para derretir fortificaciones defensivas.',
    visual: 'Traje de contención acorazado con tubos fluorescentes de ácido sulfúrico circulando por la coraza.',
    palette: ['#3b0764', '#15803d', '#bef264'],
    signatureGadget: 'Cañón Dispersor de Lluvia Ácida y Niebla Corrosiva.',
    starterElementId: 'cloruro_hierro',
    motivation: 'Destruir las infraestructuras de Nobelia para demostrar la fragilidad de los metales tradicionales.',
    weakness: 'Vulnerable a neutralizaciones instantáneas con bases alcalinas fuertes.',
    evolutionArc: 'Enfrenta al equipo de Leo en la defensa del puente levadizo.',
    avatar: '🧪'
  },
  {
    id: 'agente_radon',
    name: 'Agente Radón',
    age: 31,
    role: 'Infiltrado Espectral & Asesino de Sombras',
    category: 'sindicato',
    costCoins: 80,
    isCensored: true,
    archetype: 'Espía sigiloso e indetectable',
    catchphrase: 'No me ves, pero ya respiras mi decaimiento.',
    concept: 'Infiltrado encubierto que utiliza gases densos radiactivos para sabotear sensores y cámaras de seguridad.',
    visual: 'Traje de camuflaje óptico gris humo con capa de absorción de rayos gamma y ojos fluorescentes.',
    palette: ['#0f172a', '#475569', '#67e8f9'],
    signatureGadget: 'Emisor de Emisiones Alfa con difusor de vacío.',
    starterElementId: 'nitrogeno',
    motivation: 'Robar los archivos secretos del Mendelomnio original custodiados en la torre de la Rectora.',
    weakness: 'La ventilación forzada o campos de vacío anulan completamente su camuflaje.',
    evolutionArc: 'Es desenmascarado por Kai mediante un cálculo de densidades gaseosas en el Capítulo 8.',
    avatar: '👤'
  }
];

// --- GUÍA DE EPISODIOS TEMPORADA 1 ---
export const SEASON_1_EPISODES: EpisodeGuide[] = [
  {
    number: 1,
    title: 'Bienvenidos a Materia',
    summary: 'Leo explora el gran camino hacia Nobelia y se topa con el Fósforo Blanco inestable. Yan interviene enfriándolo con Nitrógeno. Ambos llegan a la gran metrópoli de Nobelia.',
    scientificReaction: 'Estabilización Térmica: Nitrógeno criogénico sofoca la combustión espontánea del Fósforo.',
    reactionFormula: 'P4 (blanco inestable) + N2 (frío) -> P4 (estabilizado)',
    featuredBeasts: ['hidrogeno', 'fosforo', 'nitrogeno']
  },
  {
    number: 2,
    title: 'Nuevos Amigos',
    summary: 'Leo sueña con un gran torneo y llega rezagado al discurso de apertura. El Profesor Lantan forma el equipo con Leo, Yan, Kai y Ana, otorgándoles sus elementos iniciales.',
    scientificReaction: 'Asignación de Núcleos Elementales: H (Leo), C (Yan), Fe (Ana), Si (Kai).',
    reactionFormula: 'Asignación del Cuarteto Elemental',
    featuredBeasts: ['hidrogeno', 'carbono', 'hierro', 'silicio']
  },
  {
    number: 3,
    title: 'Todo Controlado',
    summary: 'En un santuario boscoso de oxígeno, delincuentes usan Manganeso para iniciar un incendio masivo. Yan apaga las llamas con CO2. Ana y Yan combinan Hierro y Fósforo (Fe3P) para derrotar al Trióxido de Dimanganeso (Mn2O3).',
    scientificReaction: 'Sofocación por CO2 y Síntesis de Fosfuro de Hierro.',
    reactionFormula: 'Mn2O3 vs 3Fe + P -> Fe3P',
    featuredBeasts: ['oxigeno', 'manganeso', 'co2', 'fosfuro_hierro']
  },
  {
    number: 4,
    title: 'El Intruso',
    summary: 'Un huerto agrícola está petrificado por Carbonato de Magnesio (MgCO3). Kai analiza el suelo y enseña a Leo a usar Hidrógeno para romper el enlace iónico y liberar al Magnesio envuelto en vapor de agua.',
    scientificReaction: 'Disolución Ácido-Base de Carbonatos: MgCO3 + 2H -> H2O + Mg + CO2.',
    reactionFormula: 'MgCO3 + 2H -> H2O + Mg + CO2',
    featuredBeasts: ['carbonato_magnesio', 'magnesio', 'agua', 'co2']
  },
  {
    number: 5,
    title: 'El Protector',
    summary: 'Combate 2v2 escolar: Ana usa Fósforo contra Potasio formando Fosfuro de Potasio (K3P), y Leo con Yan sintetizan Óxido de Magnesio (MgO) para frenar las explosiones del Cesio. Luego salvan el hospital veterinario forjando Cementita y blindaje de silicio.',
    scientificReaction: 'Suelo refractario MgO y Forja de Cementita (Fe3C) con Cobre conductor.',
    reactionFormula: 'Mg + O -> MgO | 3Fe + C -> Fe3C',
    featuredBeasts: ['potasio', 'cesio', 'oxido_magnesio', 'cobre']
  },
  {
    number: 6,
    title: 'Levantando Puentes',
    summary: 'Un puente levadizo tiene los cables de cobre oxidados (CuO) y amenaza a unos mercaderes. Leo extrae Estaño de la Casiterita (SnO2) con Hidrógeno y repara el cableado explicando el enlace metálico (mar de electrones).',
    scientificReaction: 'Reducción de Casiterita y Mar de Electrones Cu-Sn.',
    reactionFormula: 'SnO2 + 4H -> Sn + 2H2O | Cu + Sn -> Enlace Metálico',
    featuredBeasts: ['cobre', 'estano', 'hidrogeno']
  },
  {
    number: 7,
    title: 'Daño Reparado',
    summary: 'Un travieso Sodio (Na) derriba un granero mientras el Calcio (Ca) sostiene las vigas. El equipo acorrala al Sodio en el sistema de riego y lo neutraliza con Cloro, transformándolo en Sal Común (NaCl).',
    scientificReaction: 'Neutralización Enlace Iónico: 2Na + Cl2 -> 2NaCl.',
    reactionFormula: 'Na + Cl -> NaCl (Sal común)',
    featuredBeasts: ['sodio', 'calcio', 'cloro', 'nacl']
  },
  {
    number: 8,
    title: 'Cuando el Río Suena...',
    summary: 'Unos abusones atacan a unos niños con Bario (Ba) y Sulfato de Bario (BaSO4). Ana los derrota creando Ferrosilicio (FeSi). Los niños usan Cloro y Hierro para crear Cloruro de Hierro (FeCl3) y coagular los sedimentos del río.',
    scientificReaction: 'Aleación Ferrosilicio y Floculación con FeCl3.',
    reactionFormula: 'Fe + Si -> FeSi | Fe + 3Cl -> FeCl3',
    featuredBeasts: ['bario', 'sulfato_bario', 'ferrosilicio', 'cloruro_hierro']
  },
  {
    number: 9,
    title: 'Castillos de Arena',
    summary: 'Kai invoca a Sílice (SiO2 / Arena) para filtrar el gran río, pero un rival lanza Ácido Fluorhídrico (HF) para disolver el filtro. A orden de Yan, todos invocan Calcio (Ca) para neutralizar el fluoruro y salvar el río.',
    scientificReaction: 'Ataque con Ácido Fluorhídrico y Neutralización Calcárea: 2HF + Ca -> CaF2 + H2.',
    reactionFormula: 'SiO2 + 4HF -> SiF4 + 2H2O | 2HF + Ca -> CaF2 + H2',
    featuredBeasts: ['silice_arena', 'calcio']
  },
  {
    number: 10,
    title: 'La Brecha',
    summary: 'En la antigua cantera, el Sindicato Isótopo desata al Ácido Sulfúrico (H2SO4) y a un Gólem de Bronce (CuSn). Tras un combate brutal donde todos caen exhaustos, Yan convoca a dos elementos a la vez: Carbonato Cálcico para neutralizar el ácido y Carburo de Silicio (SiC) para destruir al gólem. Tras la batalla, Yan abandona el grupo.',
    scientificReaction: 'Doble Invocación Maestra de Carbono: H2SO4 + CaCO3 -> CaSO4 + H2O + CO2 | Si + C -> SiC Abrasor.',
    reactionFormula: 'H2SO4 + CaCO3 -> CaSO4 + CO2 + H2O | Si + C -> SiC',
    featuredBeasts: ['acido_sulfurico', 'bronce', 'carbonato_calcio', 'sic_abrasor']
  }
];

// --- OBJETOS ESCANEABLES EN MUNDO REAL (ESTILO POKÉMON GO / GOOGLE LENS) ---
export const SCANNABLE_OBJECTS: ScannableObjectSample[] = [
  {
    id: 'lata_aluminio',
    name: 'Lata de Refresco Metálica',
    description: 'Envase metálico ligero con alta maleabilidad y conductividad.',
    majorityMaterial: 'Aluminio y Hierro aleado',
    formula: 'Fe / Al',
    beastId: 'hierro',
    category: 'Metal / Envase',
    icon: '🥫',
    color: '#ea580c'
  },
  {
    id: 'vaso_vidrio',
    name: 'Vaso de Vidrio / Cristal',
    description: 'Estructura amorfa de dióxido de silicio fundido a alta temperatura.',
    majorityMaterial: 'Dióxido de Silicio (Sílice)',
    formula: 'SiO2',
    beastId: 'silice_arena',
    category: 'Vidrio / Cerámica',
    icon: '🥛',
    color: '#0284c7'
  },
  {
    id: 'cable_electrico',
    name: 'Cable de Cobre Eléctrico',
    description: 'Conductor metálico rojizo con alta densidad electrónica.',
    majorityMaterial: 'Cobre Puro',
    formula: 'Cu',
    beastId: 'cobre',
    category: 'Electricidad',
    icon: '🔌',
    color: '#b45309'
  },
  {
    id: 'lapiz_grafito',
    name: 'Mina de Lápiz de Grafito',
    description: 'Láminas hexagonales de carbono puro capaz de cristalizar en diamante.',
    majorityMaterial: 'Carbono Puro (Grafito)',
    formula: 'C',
    beastId: 'carbono',
    category: 'Mineral / Oficina',
    icon: '✏️',
    color: '#334155'
  },
  {
    id: 'salero_mesa',
    name: 'Salero con Sal de Mesa',
    description: 'Cristales cúbicos de halita formados por enlace iónico alcalino.',
    majorityMaterial: 'Cloruro de Sodio',
    formula: 'NaCl',
    beastId: 'nacl',
    category: 'Alimento / Sal',
    icon: '🧂',
    color: '#94a3b8'
  },
  {
    id: 'cascara_huevo',
    name: 'Cáscara de Huevo / Tiza',
    description: 'Estructura porosa biológica rica en carbonatos de calcio.',
    majorityMaterial: 'Carbonato de Calcio',
    formula: 'CaCO3',
    beastId: 'carbonato_calcio',
    category: 'Biológico / Calcáreo',
    icon: '🥚',
    color: '#f97316'
  },
  {
    id: 'botella_agua',
    name: 'Botella de Agua Mineral',
    description: 'Solvente líquido vital con moléculas polares H-O-H.',
    majorityMaterial: 'Agua Pura y Minerales',
    formula: 'H2O',
    beastId: 'agua',
    category: 'Líquido / Bebida',
    icon: '🧴',
    color: '#0284c7'
  },
  {
    id: 'cerilla_fosforo',
    name: 'Cerilla / Fósforo de Fricción',
    description: 'Cabeza pirotécnica con sulfuro de fósforo sensible al calor.',
    majorityMaterial: 'Fósforo Rojo y Blanco',
    formula: 'P4',
    beastId: 'fosforo',
    category: 'Química / Fuego',
    icon: '🔥',
    color: '#10b981'
  },
  {
    id: 'pila_bateria',
    name: 'Pila / Acumulador Alcalino',
    description: 'Célula electroquímica densa con metales alcalinos reactivos.',
    majorityMaterial: 'Metales Alcalinos (Cesio / Litio / Potasio)',
    formula: 'Cs / K',
    beastId: 'cesio',
    category: 'Tecnología',
    icon: '🔋',
    color: '#eab308'
  },
  {
    id: 'maceta_fertilizante',
    name: 'Sustrato Agrícola / Maceta',
    description: 'Tierra enriquecida con sales minerales y carbonato de magnesio.',
    majorityMaterial: 'Carbonato de Magnesio',
    formula: 'MgCO3',
    beastId: 'carbonato_magnesio',
    category: 'Agricultura / Tierra',
    icon: '🪴',
    color: '#7dd3fc'
  },
  {
    id: 'clavo_oxidado',
    name: 'Clavo Férreo Oxidado',
    description: 'Vástago metálico que ha sufrido corrosión redox por contacto con oxígeno.',
    majorityMaterial: 'Óxido de Hierro y Hierro',
    formula: 'Fe2O3 / Fe',
    beastId: 'hierro',
    category: 'Herramienta / Construcción',
    icon: '🔩',
    color: '#ea580c'
  },
  {
    id: 'disco_corte',
    name: 'Disco de Corte Abrasivo / Cerámica',
    description: 'Material cerámico de dureza 9.5 Mohs para blindajes y corte.',
    majorityMaterial: 'Carburo de Silicio',
    formula: 'SiC',
    beastId: 'sic_abrasor',
    category: 'Industrial',
    icon: '⚙️',
    color: '#38bdf8'
  }
];
